/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.DisplayName;

class AppTest {

    @Test
    @DisplayName("Grade 70 should return true for passing")
    void testPassingGrade() {
        LehmanGradeBook gb = new LehmanGradeBook();
        assertTrue(gb.isPassing(70), "A grade of 70 should pass.");

        assertEquals('A', gb.getLetterGrade(95));
        assertEquals('F', gb.getLetterGrade(50));

    }

    @Test
    void testInvalidGradeThrowsException() {
        LehmanGradeBook gb = new LehmanGradeBook();
        assertThrows(IllegalArgumentException.class, () -> {
            gb.isPassing(150);
        });
    }

}
